Don't run as root user
First time running with as-is code gave following error, hence, fixed the code:
Error: container's runAsUser breaks non-root policy